ARG registry
ARG repository
ARG tag
ARG release

FROM ${registry}/${repository}:${tag}-${release}

COPY rootfs/ /

ARG nexus_version=3.29.2-02

RUN mkdir /usr/sonatype\
 && cd /usr/sonatype\
 && curl -L https://download.sonatype.com/nexus/3/nexus-${nexus_version}-unix.tar.gz|tar zx\
 && systemctl enable nexus-chown.service nexus.service

EXPOSE 8081/tcp

VOLUME [ "/var/lib/nexus/sonatype-work" ]
