ARG registry
ARG repository
ARG tag
ARG release

FROM ${registry}/${repository}:${tag}-${release}

RUN dnf -yq module disable php:7.2 nginx:1.14\
 && dnf -yq module enable nginx:1.18\
 && dnf -yq install --setopt=install_weak_deps=False --nodocs nginx\
 && systemctl enable nginx.service\
 && dnf -yq clean all\
 && rm -rf /var/cache/* /var/log/dnf* /var/log/hawkey* /var/log/rhsm/

COPY rootfs/ /

EXPOSE 80/tcp
