ARG registry
ARG repository
ARG tag
ARG release

FROM ${registry}/${repository}:${tag}-${release}

RUN dnf -yq module enable nodejs:14\
 && dnf -yq install --setopt=install_weak_deps=False --nodocs nodejs npm\
 && dnf -yq clean all\
 && rm -rf /var/cache/* /var/log/dnf* /var/log/hawkey* /var/log/rhsm/
