ARG registry=registry.access.redhat.com
ARG repository=ubi8/ubi
ARG tag=8.3

FROM ${registry}/${repository}:${tag}

COPY rootfs/ /

RUN dnf -y clean all\
 && dnf config-manager --set-disabled ubi*\
 && dnf -y update --setopt=install_weak_deps=False --nodocs rpm\* dnf\*\
 && dnf -y update --setopt=install_weak_deps=False --nodocs\
 && dnf -y clean all\
 && rm -rf /var/log/dnf* /var/log/hawkey* /var/log/rhsm/\
 && rm -rf /var/cache/*
