ARG registry
ARG repository
ARG tag
ARG release

FROM ${registry}/${repository}:${tag}-${release}

COPY rootfs/ /

RUN dnf -y install --setopt=install_weak_deps=False --nodocs openssh-server openssh-clients\
 && dnf -y clean all\
 && rm -rf /var/log/dnf* /var/log/hawkey* /var/log/rhsm/\
 && rm -rf /var/cache/*
